##HDFS文件系统服务器的地址以及端口
hdfs:
  path: hdfs://10.3.6.124:8020
  user: root

###swagger配置（有yml配置和class配置两种方式，本demo采用class配置）
#swagger:
#  ##是否开启swagger文档
#  enable: true
#  ##接口包(多个用,隔开)
#  basePackage: com.szewec.controller
#  ##文档标题
#  title: HDFS目录和文件管理
#  ##文档描述
#  description: HDFS目录和文件管理
#  ##文档版本
#  version: 1.0.0
